wandb_version: 1

gpu:
  desc: null
  value: 0
mode:
  desc: null
  value: ft
dataset:
  desc: null
  value: 0
model:
  desc: null
  value: 0
root:
  desc: null
  value: D:\ML\Dataset/
log_file:
  desc: null
  value: D:\ML\Projects\MyTransferLearning-wangjindong-\code\Myclip/log/ft_RN50_dataset_OfficeHome_Art.txt
seed:
  desc: null
  value: 42
result:
  desc: null
  value: false
batchsize:
  desc: null
  value: 16
nepoch:
  desc: null
  value: 30
lr:
  desc: null
  value: 1.0e-05
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.98
eps:
  desc: null
  value: 1.0e-06
weight_decay:
  desc: null
  value: 0.2
test_batchsize:
  desc: null
  value: 16
test_data:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708415913.765754
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.15.8
      8:
      - 3
      - 5
